# -*- coding: utf-8 -*-
"""exercicios_T10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GK_2bNYtgBrH6dY5wJGy5pCApInsdPcV

aulas dos primeiros scrips
"""

#exercicios1
# Criando uma lista de alimentos
frutas = ["maçã", "laranja", "pitaia",]

# Exibindo a lista completa
print(f"Lista de alunos: {frutas}")

# Acessando o primeiro elemento (indice 0)
print(f"Primeiro aluno: {frutas[0]}")
print(f"ultimo aluno: {frutas[-1]}")

#exercicios2
# Criando uma tupla com as estacoes do ano
estacoes = ("Verao", "Inverno", "Primavera", "Inverno")

# Exibindo a tupla completa
print(estacoes)

# Acessando elementos por indice (comeca em 0)
print(f"Primeira estação: {estacoes[0]}")
print(f"Ultima estação: {estacoes[-1]}")

#exercicio3
# Criando um dicionario com informacoes de uma pessoa
pessoa = {
    "nome": "bia",
    "idade": "17",
    "cidade": "maceio"
}

print(pessoa)

#desafio
# Criando uma tupla com as estacoes do ano
animais = ["gato", "tartaruga", "narval"]

# Exibindo a tupla completa
print(animais)

# Acessando elementos por indice (comeca em 0)
print(f"Primeira estação: {animais[0]}")
print(f"Ultima estação: {animais[-1]}")

animais.append("raposa")
print(f"apos adicionar: {animais}")